#   Agregar elementos a un conjunto add()
print("Creacion de set por medio de tuplas")
arco_iris = {"Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Añil"}
print(f"El contenido de la variable arco_iris {arco_iris}")
print(f"Cantidad de elementos de la variable arco_iris {len(arco_iris)})")
print(f"Tipo de datos de la variable arco_iris {type(arco_iris)}")
arco_iris.add("Violeta")
print(f"El contenido de la variable arco_iris {arco_iris}")
print(f"Cantidad de elementos de la variable arco_iris {len(arco_iris)})")
print(f"Tipo de datos de la variable arco_iris {type(arco_iris)}")
arco_iris.add("Violeta")
arco_iris.add("Violeta")
print(f"El contenido de la variable arco_iris {arco_iris}")
print(f"Cantidad de elementos de la variable arco_iris {len(arco_iris)})")
print(f"Tipo de datos de la variable arco_iris {type(arco_iris)}")
