# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video467.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaludoVentana(object):
    def setupUi(self, SaludoVentana):
        SaludoVentana.setObjectName("SaludoVentana")
        SaludoVentana.resize(320, 240)
        self.wdg_principal = QtWidgets.QWidget(SaludoVentana)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_nombre = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_nombre.setGeometry(QtCore.QRect(10, 40, 151, 18))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.txt_nombre = QtWidgets.QLineEdit(self.wdg_principal)
        self.txt_nombre.setGeometry(QtCore.QRect(160, 35, 151, 21))
        self.txt_nombre.setObjectName("txt_nombre")
        self.btn_saludar = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_saludar.setGeometry(QtCore.QRect(160, 80, 151, 26))
        self.btn_saludar.setObjectName("btn_saludar")
        SaludoVentana.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(SaludoVentana)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        SaludoVentana.setMenuBar(self.mbr_principal)
        self.stb_principal = QtWidgets.QStatusBar(SaludoVentana)
        self.stb_principal.setObjectName("stb_principal")
        SaludoVentana.setStatusBar(self.stb_principal)

        self.retranslateUi(SaludoVentana)
        QtCore.QMetaObject.connectSlotsByName(SaludoVentana)

    def retranslateUi(self, SaludoVentana):
        _translate = QtCore.QCoreApplication.translate
        SaludoVentana.setWindowTitle(_translate("SaludoVentana", "Saludo"))
        self.lbl_nombre.setText(_translate("SaludoVentana", "Escriba su Nombre:"))
        self.btn_saludar.setText(_translate("SaludoVentana", "Saludar"))
