# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video-479.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Diagnosticos(object):
    def setupUi(self, Diagnosticos):
        Diagnosticos.setObjectName("Diagnosticos")
        Diagnosticos.resize(320, 240)
        Diagnosticos.setMinimumSize(QtCore.QSize(320, 240))
        Diagnosticos.setMaximumSize(QtCore.QSize(320, 240))
        self.verticalLayoutWidget = QtWidgets.QWidget(Diagnosticos)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_diagnosticos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_diagnosticos.setContentsMargins(10, 10, 10, 0)
        self.lay_ver_diagnosticos.setObjectName("lay_ver_diagnosticos")
        self.lbl_seleccion_diagnosticos = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion_diagnosticos.setObjectName("lbl_seleccion_diagnosticos")
        self.lay_ver_diagnosticos.addWidget(self.lbl_seleccion_diagnosticos)
        self.lst_diagnosticos = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lst_diagnosticos.setObjectName("lst_diagnosticos")
        item = QtWidgets.QListWidgetItem()
        self.lst_diagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lst_diagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lst_diagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lst_diagnosticos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lst_diagnosticos.addItem(item)
        self.lay_ver_diagnosticos.addWidget(self.lst_diagnosticos)
        self.lbl_diagnostico_seleccionado = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_diagnostico_seleccionado.setText("")
        self.lbl_diagnostico_seleccionado.setObjectName("lbl_diagnostico_seleccionado")
        self.lay_ver_diagnosticos.addWidget(self.lbl_diagnostico_seleccionado)
        self.lay_ver_diagnosticos.setStretch(0, 1)
        self.lay_ver_diagnosticos.setStretch(1, 2)
        self.lay_ver_diagnosticos.setStretch(2, 1)

        self.retranslateUi(Diagnosticos)
        QtCore.QMetaObject.connectSlotsByName(Diagnosticos)

    def retranslateUi(self, Diagnosticos):
        _translate = QtCore.QCoreApplication.translate
        Diagnosticos.setWindowTitle(_translate("Diagnosticos", "Diagnosticos"))
        self.lbl_seleccion_diagnosticos.setText(_translate("Diagnosticos", "Seleccione el diagnostico:"))
        __sortingEnabled = self.lst_diagnosticos.isSortingEnabled()
        self.lst_diagnosticos.setSortingEnabled(False)
        item = self.lst_diagnosticos.item(0)
        item.setText(_translate("Diagnosticos", "Rayos X - $5"))
        item = self.lst_diagnosticos.item(1)
        item.setText(_translate("Diagnosticos", "Nivel de Azucar - $3"))
        item = self.lst_diagnosticos.item(2)
        item.setText(_translate("Diagnosticos", "Prueba de hemoglobina - $7"))
        item = self.lst_diagnosticos.item(3)
        item.setText(_translate("Diagnosticos", "Analisis de Orina -$8"))
        item = self.lst_diagnosticos.item(4)
        item.setText(_translate("Diagnosticos", "Analisis de PSA - $10"))
        self.lst_diagnosticos.setSortingEnabled(__sortingEnabled)
