# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video-469/video469.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentaVentana(object):
    def setupUi(self, VentaVentana):
        VentaVentana.setObjectName("VentaVentana")
        VentaVentana.resize(480, 640)
        self.wdg_principal = QtWidgets.QWidget(VentaVentana)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_seleccion = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_seleccion.setGeometry(QtCore.QRect(10, 380, 431, 18))
        self.lbl_seleccion.setText("")
        self.lbl_seleccion.setObjectName("lbl_seleccion")
        self.gpb_camisa = QtWidgets.QGroupBox(self.wdg_principal)
        self.gpb_camisa.setGeometry(QtCore.QRect(10, 10, 231, 151))
        self.gpb_camisa.setObjectName("gpb_camisa")
        self.rbn_m = QtWidgets.QRadioButton(self.gpb_camisa)
        self.rbn_m.setGeometry(QtCore.QRect(10, 30, 118, 24))
        self.rbn_m.setObjectName("rbn_m")
        self.rbn_l = QtWidgets.QRadioButton(self.gpb_camisa)
        self.rbn_l.setGeometry(QtCore.QRect(10, 60, 118, 24))
        self.rbn_l.setObjectName("rbn_l")
        self.rbn_xl = QtWidgets.QRadioButton(self.gpb_camisa)
        self.rbn_xl.setGeometry(QtCore.QRect(10, 90, 118, 24))
        self.rbn_xl.setObjectName("rbn_xl")
        self.rbn_xll = QtWidgets.QRadioButton(self.gpb_camisa)
        self.rbn_xll.setGeometry(QtCore.QRect(10, 120, 118, 24))
        self.rbn_xll.setObjectName("rbn_xll")
        self.gpb_metodo_pago = QtWidgets.QGroupBox(self.wdg_principal)
        self.gpb_metodo_pago.setGeometry(QtCore.QRect(10, 170, 301, 191))
        self.gpb_metodo_pago.setObjectName("gpb_metodo_pago")
        self.rbn_tarjeta_credito_debito = QtWidgets.QRadioButton(self.gpb_metodo_pago)
        self.rbn_tarjeta_credito_debito.setGeometry(QtCore.QRect(10, 30, 191, 24))
        self.rbn_tarjeta_credito_debito.setObjectName("rbn_tarjeta_credito_debito")
        self.rbn_pago_contra_entrega = QtWidgets.QRadioButton(self.gpb_metodo_pago)
        self.rbn_pago_contra_entrega.setGeometry(QtCore.QRect(10, 60, 181, 24))
        self.rbn_pago_contra_entrega.setObjectName("rbn_pago_contra_entrega")
        self.rbn_consigna_bancaria = QtWidgets.QRadioButton(self.gpb_metodo_pago)
        self.rbn_consigna_bancaria.setGeometry(QtCore.QRect(10, 90, 171, 24))
        self.rbn_consigna_bancaria.setObjectName("rbn_consigna_bancaria")
        self.rbn_efectivo = QtWidgets.QRadioButton(self.gpb_metodo_pago)
        self.rbn_efectivo.setGeometry(QtCore.QRect(10, 120, 118, 24))
        self.rbn_efectivo.setObjectName("rbn_efectivo")
        VentaVentana.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(VentaVentana)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 480, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        VentaVentana.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(VentaVentana)
        self.stt_principal.setObjectName("stt_principal")
        VentaVentana.setStatusBar(self.stt_principal)

        self.retranslateUi(VentaVentana)
        QtCore.QMetaObject.connectSlotsByName(VentaVentana)

    def retranslateUi(self, VentaVentana):
        _translate = QtCore.QCoreApplication.translate
        VentaVentana.setWindowTitle(_translate("VentaVentana", "Venta"))
        self.gpb_camisa.setTitle(_translate("VentaVentana", "Escoja la talla de su camisa:"))
        self.rbn_m.setText(_translate("VentaVentana", "M"))
        self.rbn_l.setText(_translate("VentaVentana", "L"))
        self.rbn_xl.setText(_translate("VentaVentana", "XL"))
        self.rbn_xll.setText(_translate("VentaVentana", "XLL"))
        self.gpb_metodo_pago.setTitle(_translate("VentaVentana", "Seleccione su metodo de pago:"))
        self.rbn_tarjeta_credito_debito.setText(_translate("VentaVentana", "Tarjeta Debito/Credito"))
        self.rbn_pago_contra_entrega.setText(_translate("VentaVentana", "Pago Contraentrega"))
        self.rbn_consigna_bancaria.setText(_translate("VentaVentana", "Consigna Bancaria"))
        self.rbn_efectivo.setText(_translate("VentaVentana", "Efectivo"))
