# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video-474.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Heladeria(object):
    def setupUi(self, Heladeria):
        Heladeria.setObjectName("Heladeria")
        Heladeria.resize(480, 640)
        self.wdg_principal = QtWidgets.QWidget(Heladeria)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_titulo = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_titulo.setGeometry(QtCore.QRect(180, 30, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_seleccion_helado = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_seleccion_helado.setGeometry(QtCore.QRect(40, 100, 171, 18))
        self.lbl_seleccion_helado.setObjectName("lbl_seleccion_helado")
        self.lbl_seleccion_bebida = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_seleccion_bebida.setGeometry(QtCore.QRect(250, 100, 171, 18))
        self.lbl_seleccion_bebida.setObjectName("lbl_seleccion_bebida")
        self.gbx_helados = QtWidgets.QGroupBox(self.wdg_principal)
        self.gbx_helados.setGeometry(QtCore.QRect(30, 140, 181, 171))
        self.gbx_helados.setObjectName("gbx_helados")
        self.chk_chocolate = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_chocolate.setGeometry(QtCore.QRect(10, 30, 131, 24))
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.chk_vainilla = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_vainilla.setGeometry(QtCore.QRect(10, 60, 99, 24))
        self.chk_vainilla.setObjectName("chk_vainilla")
        self.chk_arequipe = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_arequipe.setGeometry(QtCore.QRect(10, 90, 151, 24))
        self.chk_arequipe.setObjectName("chk_arequipe")
        self.chk_ron_pasas = QtWidgets.QCheckBox(self.gbx_helados)
        self.chk_ron_pasas.setGeometry(QtCore.QRect(10, 120, 161, 24))
        self.chk_ron_pasas.setObjectName("chk_ron_pasas")
        self.gbx_bebida = QtWidgets.QGroupBox(self.wdg_principal)
        self.gbx_bebida.setGeometry(QtCore.QRect(250, 140, 111, 131))
        self.gbx_bebida.setObjectName("gbx_bebida")
        self.chk_cafe = QtWidgets.QCheckBox(self.gbx_bebida)
        self.chk_cafe.setGeometry(QtCore.QRect(10, 30, 99, 24))
        self.chk_cafe.setObjectName("chk_cafe")
        self.chk_agua = QtWidgets.QCheckBox(self.gbx_bebida)
        self.chk_agua.setGeometry(QtCore.QRect(10, 60, 99, 24))
        self.chk_agua.setObjectName("chk_agua")
        self.chk_soda = QtWidgets.QCheckBox(self.gbx_bebida)
        self.chk_soda.setGeometry(QtCore.QRect(10, 90, 99, 24))
        self.chk_soda.setObjectName("chk_soda")
        self.lbl_total = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_total.setGeometry(QtCore.QRect(40, 360, 131, 18))
        self.lbl_total.setObjectName("lbl_total")
        Heladeria.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(Heladeria)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 480, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        Heladeria.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(Heladeria)
        self.stt_principal.setObjectName("stt_principal")
        Heladeria.setStatusBar(self.stt_principal)

        self.retranslateUi(Heladeria)
        QtCore.QMetaObject.connectSlotsByName(Heladeria)

    def retranslateUi(self, Heladeria):
        _translate = QtCore.QCoreApplication.translate
        Heladeria.setWindowTitle(_translate("Heladeria", "Heladeria"))
        self.lbl_titulo.setText(_translate("Heladeria", "Menu"))
        self.lbl_seleccion_helado.setText(_translate("Heladeria", "Seleccione su helado:"))
        self.lbl_seleccion_bebida.setText(_translate("Heladeria", "Seleccione su bebida:"))
        self.gbx_helados.setTitle(_translate("Heladeria", "Helados []"))
        self.chk_chocolate.setText(_translate("Heladeria", "Chocolate $3"))
        self.chk_vainilla.setText(_translate("Heladeria", "Vainilla $2"))
        self.chk_arequipe.setText(_translate("Heladeria", "Arequipe $3"))
        self.chk_ron_pasas.setText(_translate("Heladeria", "Ron con pasas $4"))
        self.gbx_bebida.setTitle(_translate("Heladeria", "Bebidas []"))
        self.chk_cafe.setText(_translate("Heladeria", "Cafe $2"))
        self.chk_agua.setText(_translate("Heladeria", "Agua $1"))
        self.chk_soda.setText(_translate("Heladeria", "Soda $3"))
        self.lbl_total.setText(_translate("Heladeria", "Total: $0"))
