# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video-483.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lenguajes(object):
    def setupUi(self, Lenguajes):
        Lenguajes.setObjectName("Lenguajes")
        Lenguajes.resize(420, 190)
        Lenguajes.setMinimumSize(QtCore.QSize(420, 190))
        Lenguajes.setMaximumSize(QtCore.QSize(420, 190))
        self.verticalLayoutWidget = QtWidgets.QWidget(Lenguajes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lay_frm_entrada = QtWidgets.QFormLayout()
        self.lay_frm_entrada.setObjectName("lay_frm_entrada")
        self.lbl_seleccion_lenguajes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion_lenguajes.setObjectName("lbl_seleccion_lenguajes")
        self.lay_frm_entrada.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_seleccion_lenguajes)
        self.cbx_lenguajes = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx_lenguajes.setObjectName("cbx_lenguajes")
        self.cbx_lenguajes.addItem("")
        self.cbx_lenguajes.addItem("")
        self.cbx_lenguajes.addItem("")
        self.cbx_lenguajes.addItem("")
        self.cbx_lenguajes.addItem("")
        self.cbx_lenguajes.addItem("")
        self.lay_frm_entrada.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbx_lenguajes)
        self.lay_hor_secundario = QtWidgets.QFormLayout()
        self.lay_hor_secundario.setObjectName("lay_hor_secundario")
        self.lbl_seleccion = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion.setText("")
        self.lbl_seleccion.setObjectName("lbl_seleccion")
        self.lay_hor_secundario.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_seleccion)
        self.lay_frm_entrada.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.lay_hor_secundario)
        self.lay_ver_principal.addLayout(self.lay_frm_entrada)

        self.retranslateUi(Lenguajes)
        QtCore.QMetaObject.connectSlotsByName(Lenguajes)

    def retranslateUi(self, Lenguajes):
        _translate = QtCore.QCoreApplication.translate
        Lenguajes.setWindowTitle(_translate("Lenguajes", "Seleccion Lenguaje"))
        self.lbl_seleccion_lenguajes.setText(_translate("Lenguajes", "Lenguaje de programacion"))
        self.cbx_lenguajes.setItemText(0, _translate("Lenguajes", "Python"))
        self.cbx_lenguajes.setItemText(1, _translate("Lenguajes", "C"))
        self.cbx_lenguajes.setItemText(2, _translate("Lenguajes", "Go"))
        self.cbx_lenguajes.setItemText(3, _translate("Lenguajes", "C++"))
        self.cbx_lenguajes.setItemText(4, _translate("Lenguajes", "Rust"))
        self.cbx_lenguajes.setItemText(5, _translate("Lenguajes", "JavaScript"))
