# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video488.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RelojDigital(object):
    def setupUi(self, RelojDigital):
        RelojDigital.setObjectName("RelojDigital")
        RelojDigital.resize(320, 200)
        RelojDigital.setMinimumSize(QtCore.QSize(320, 200))
        RelojDigital.setMaximumSize(QtCore.QSize(320, 200))
        self.verticalLayoutWidget = QtWidgets.QWidget(RelojDigital)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lcd_hora = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcd_hora.setObjectName("lcd_hora")
        self.lay_ver_principal.addWidget(self.lcd_hora)

        self.retranslateUi(RelojDigital)
        QtCore.QMetaObject.connectSlotsByName(RelojDigital)

    def retranslateUi(self, RelojDigital):
        _translate = QtCore.QCoreApplication.translate
        RelojDigital.setWindowTitle(_translate("RelojDigital", "Reloj Digital"))
