# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video471.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pizzeria(object):
    def setupUi(self, Pizzeria):
        Pizzeria.setObjectName("Pizzeria")
        Pizzeria.resize(300, 340)
        self.wdg_principal = QtWidgets.QWidget(Pizzeria)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_precio_base_pizza = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_precio_base_pizza.setGeometry(QtCore.QRect(20, 20, 151, 51))
        self.lbl_precio_base_pizza.setObjectName("lbl_precio_base_pizza")
        self.lbl_seleccion_extras = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_seleccion_extras.setGeometry(QtCore.QRect(20, 90, 151, 21))
        self.lbl_seleccion_extras.setObjectName("lbl_seleccion_extras")
        self.chk_queso = QtWidgets.QCheckBox(self.wdg_principal)
        self.chk_queso.setGeometry(QtCore.QRect(20, 130, 121, 24))
        self.chk_queso.setObjectName("chk_queso")
        self.chk_aceitunas = QtWidgets.QCheckBox(self.wdg_principal)
        self.chk_aceitunas.setGeometry(QtCore.QRect(20, 160, 151, 24))
        self.chk_aceitunas.setObjectName("chk_aceitunas")
        self.chk_salsas = QtWidgets.QCheckBox(self.wdg_principal)
        self.chk_salsas.setGeometry(QtCore.QRect(20, 190, 131, 24))
        self.chk_salsas.setObjectName("chk_salsas")
        self.lbl_precio_final = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_precio_final.setGeometry(QtCore.QRect(20, 250, 131, 18))
        self.lbl_precio_final.setObjectName("lbl_precio_final")
        Pizzeria.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(Pizzeria)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 300, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        Pizzeria.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(Pizzeria)
        self.stt_principal.setObjectName("stt_principal")
        Pizzeria.setStatusBar(self.stt_principal)

        self.retranslateUi(Pizzeria)
        QtCore.QMetaObject.connectSlotsByName(Pizzeria)

    def retranslateUi(self, Pizzeria):
        _translate = QtCore.QCoreApplication.translate
        Pizzeria.setWindowTitle(_translate("Pizzeria", "MainWindow"))
        self.lbl_precio_base_pizza.setText(_translate("Pizzeria", "Precio Pizza: $15"))
        self.lbl_seleccion_extras.setText(_translate("Pizzeria", "Seleccione extras:"))
        self.chk_queso.setText(_translate("Pizzeria", "Queso - $1"))
        self.chk_aceitunas.setText(_translate("Pizzeria", "Aceitunas - $2"))
        self.chk_salsas.setText(_translate("Pizzeria", "Salsas - $1"))
        self.lbl_precio_final.setText(_translate("Pizzeria", "Precio Final: $15"))
