# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video-462/video-462.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_saludar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saludar.setGeometry(QtCore.QRect(130, 200, 94, 26))
        self.btn_saludar.setToolTip("")
        self.btn_saludar.setObjectName("btn_saludar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.mbr_principal = QtWidgets.QMenuBar(MainWindow)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        MainWindow.setMenuBar(self.mbr_principal)
        self.sbr_estado = QtWidgets.QStatusBar(MainWindow)
        self.sbr_estado.setObjectName("sbr_estado")
        MainWindow.setStatusBar(self.sbr_estado)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saludo"))
        self.btn_saludar.setText(_translate("MainWindow", "Saludar"))
