# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video468.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeleccionVuelo(object):
    def setupUi(self, SeleccionVuelo):
        SeleccionVuelo.setObjectName("SeleccionVuelo")
        SeleccionVuelo.resize(309, 240)
        self.wdg_principal = QtWidgets.QWidget(SeleccionVuelo)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_escoger_clase_vuelo = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_escoger_clase_vuelo.setGeometry(QtCore.QRect(10, 10, 201, 18))
        self.lbl_escoger_clase_vuelo.setObjectName("lbl_escoger_clase_vuelo")
        self.rbn_primera_clase = QtWidgets.QRadioButton(self.wdg_principal)
        self.rbn_primera_clase.setGeometry(QtCore.QRect(10, 30, 211, 24))
        self.rbn_primera_clase.setObjectName("rbn_primera_clase")
        self.rbn_clase_negocio = QtWidgets.QRadioButton(self.wdg_principal)
        self.rbn_clase_negocio.setGeometry(QtCore.QRect(10, 60, 221, 24))
        self.rbn_clase_negocio.setObjectName("rbn_clase_negocio")
        self.rbn_clase_economica = QtWidgets.QRadioButton(self.wdg_principal)
        self.rbn_clase_economica.setGeometry(QtCore.QRect(10, 90, 221, 24))
        self.rbn_clase_economica.setObjectName("rbn_clase_economica")
        self.lbl_resultado_seleccion = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_resultado_seleccion.setGeometry(QtCore.QRect(0, 170, 301, 18))
        self.lbl_resultado_seleccion.setText("")
        self.lbl_resultado_seleccion.setObjectName("lbl_resultado_seleccion")
        SeleccionVuelo.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(SeleccionVuelo)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 309, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        SeleccionVuelo.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(SeleccionVuelo)
        self.stt_principal.setObjectName("stt_principal")
        SeleccionVuelo.setStatusBar(self.stt_principal)

        self.retranslateUi(SeleccionVuelo)
        QtCore.QMetaObject.connectSlotsByName(SeleccionVuelo)

    def retranslateUi(self, SeleccionVuelo):
        _translate = QtCore.QCoreApplication.translate
        SeleccionVuelo.setWindowTitle(_translate("SeleccionVuelo", "Seleccion Vuelo"))
        self.lbl_escoger_clase_vuelo.setText(_translate("SeleccionVuelo", "Escoja la clase del vuelo:"))
        self.rbn_primera_clase.setText(_translate("SeleccionVuelo", "Primera Clase: $190USD"))
        self.rbn_clase_negocio.setText(_translate("SeleccionVuelo", "Clase Negocios: $130USD"))
        self.rbn_clase_economica.setText(_translate("SeleccionVuelo", "Clase Economica: $99USD"))
