# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video476.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        Calculadora.setObjectName("Calculadora")
        Calculadora.resize(320, 240)
        self.wdg_principal = QtWidgets.QWidget(Calculadora)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_primer_numero = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_primer_numero.setGeometry(QtCore.QRect(0, 0, 181, 18))
        self.lbl_primer_numero.setObjectName("lbl_primer_numero")
        self.lbl_segundo_numero = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_segundo_numero.setGeometry(QtCore.QRect(0, 40, 191, 18))
        self.lbl_segundo_numero.setObjectName("lbl_segundo_numero")
        self.txt_primer_numero = QtWidgets.QLineEdit(self.wdg_principal)
        self.txt_primer_numero.setGeometry(QtCore.QRect(180, 0, 131, 26))
        self.txt_primer_numero.setObjectName("txt_primer_numero")
        self.txt_segundo_numero = QtWidgets.QLineEdit(self.wdg_principal)
        self.txt_segundo_numero.setGeometry(QtCore.QRect(190, 30, 113, 26))
        self.txt_segundo_numero.setObjectName("txt_segundo_numero")
        self.btn_sumar = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_sumar.setGeometry(QtCore.QRect(0, 70, 61, 31))
        self.btn_sumar.setObjectName("btn_sumar")
        self.btn_restar = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_restar.setGeometry(QtCore.QRect(80, 70, 61, 31))
        self.btn_restar.setObjectName("btn_restar")
        self.btn_multiplicar = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_multiplicar.setGeometry(QtCore.QRect(160, 70, 71, 31))
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.btn_dividir = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_dividir.setGeometry(QtCore.QRect(250, 70, 61, 31))
        self.btn_dividir.setObjectName("btn_dividir")
        self.label_3 = QtWidgets.QLabel(self.wdg_principal)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 101, 18))
        self.label_3.setObjectName("label_3")
        Calculadora.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(Calculadora)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.mbr_principal.setObjectName("mbr_principal")
        Calculadora.setMenuBar(self.mbr_principal)

        self.retranslateUi(Calculadora)
        QtCore.QMetaObject.connectSlotsByName(Calculadora)

    def retranslateUi(self, Calculadora):
        _translate = QtCore.QCoreApplication.translate
        Calculadora.setWindowTitle(_translate("Calculadora", "Calculadora"))
        self.lbl_primer_numero.setText(
            _translate("Calculadora", "Ingrese primer numero")
        )
        self.lbl_segundo_numero.setText(
            _translate("Calculadora", "Ingrese segundo numero")
        )
        self.btn_sumar.setText(_translate("Calculadora", "+"))
        self.btn_restar.setText(_translate("Calculadora", "-"))
        self.btn_multiplicar.setText(_translate("Calculadora", "*"))
        self.btn_dividir.setText(_translate("Calculadora", "/"))
        self.label_3.setText(_translate("Calculadora", ""))
