# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video475.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegnialesSlots(object):
    def setupUi(self, SegnialesSlots):
        SegnialesSlots.setObjectName("SegnialesSlots")
        SegnialesSlots.resize(496, 472)
        self.centralwidget = QtWidgets.QWidget(SegnialesSlots)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_vert_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_vert_principal.setContentsMargins(5, 5, 5, 5)
        self.lay_vert_principal.setObjectName("lay_vert_principal")
        self.txt_fuente = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_fuente.setObjectName("txt_fuente")
        self.lay_vert_principal.addWidget(self.txt_fuente)
        self.btn_copiar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_copiar.setObjectName("btn_copiar")
        self.lay_vert_principal.addWidget(self.btn_copiar)
        self.btn_pegar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_pegar.setObjectName("btn_pegar")
        self.lay_vert_principal.addWidget(self.btn_pegar)
        self.txt_destino = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_destino.setReadOnly(True)
        self.txt_destino.setObjectName("txt_destino")
        self.lay_vert_principal.addWidget(self.txt_destino)
        SegnialesSlots.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SegnialesSlots)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 23))
        self.menubar.setObjectName("menubar")
        SegnialesSlots.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SegnialesSlots)
        self.statusbar.setObjectName("statusbar")
        SegnialesSlots.setStatusBar(self.statusbar)

        self.retranslateUi(SegnialesSlots)
        self.btn_copiar.pressed.connect(self.txt_fuente.selectAll) # type: ignore
        self.btn_copiar.released.connect(self.txt_fuente.copy) # type: ignore
        self.btn_pegar.clicked.connect(self.txt_destino.paste) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SegnialesSlots)

    def retranslateUi(self, SegnialesSlots):
        _translate = QtCore.QCoreApplication.translate
        SegnialesSlots.setWindowTitle(_translate("SegnialesSlots", "Señales y Slots"))
        self.btn_copiar.setText(_translate("SegnialesSlots", "Copiar"))
        self.btn_pegar.setText(_translate("SegnialesSlots", "Pegar"))
