# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video472.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InicioSesion(object):
    def setupUi(self, InicioSesion):
        InicioSesion.setObjectName("InicioSesion")
        InicioSesion.resize(320, 232)
        self.wdg_principal = QtWidgets.QWidget(InicioSesion)
        self.wdg_principal.setObjectName("wdg_principal")
        self.lbl_datos_acceso = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_datos_acceso.setGeometry(QtCore.QRect(80, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_datos_acceso.setFont(font)
        self.lbl_datos_acceso.setObjectName("lbl_datos_acceso")
        self.formLayoutWidget = QtWidgets.QWidget(self.wdg_principal)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 50, 311, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.frmlay_inicio_sesion = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.frmlay_inicio_sesion.setContentsMargins(0, 0, 0, 0)
        self.frmlay_inicio_sesion.setObjectName("frmlay_inicio_sesion")
        self.lbl_nombre_usuario = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_nombre_usuario.setObjectName("lbl_nombre_usuario")
        self.frmlay_inicio_sesion.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_usuario)
        self.txt_nombre_usuario = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_nombre_usuario.setObjectName("txt_nombre_usuario")
        self.frmlay_inicio_sesion.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_usuario)
        self.lbl_contrasegnia = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_contrasegnia.setObjectName("lbl_contrasegnia")
        self.frmlay_inicio_sesion.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_contrasegnia)
        self.txt_contrasegnia = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_contrasegnia.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_contrasegnia.setObjectName("txt_contrasegnia")
        self.frmlay_inicio_sesion.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_contrasegnia)
        self.btn_iniciar_sesion = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_iniciar_sesion.setObjectName("pushButton")
        self.frmlay_inicio_sesion.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_iniciar_sesion)
        InicioSesion.setCentralWidget(self.wdg_principal)
        self.menubar = QtWidgets.QMenuBar(InicioSesion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.menubar.setObjectName("menubar")
        InicioSesion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InicioSesion)
        self.statusbar.setObjectName("statusbar")
        InicioSesion.setStatusBar(self.statusbar)

        self.retranslateUi(InicioSesion)
        QtCore.QMetaObject.connectSlotsByName(InicioSesion)

    def retranslateUi(self, InicioSesion):
        _translate = QtCore.QCoreApplication.translate
        InicioSesion.setWindowTitle(_translate("InicioSesion", "Inicio Sesion"))
        self.lbl_datos_acceso.setText(_translate("InicioSesion", "Datos de Acceso"))
        self.lbl_nombre_usuario.setText(_translate("InicioSesion", "Nombre de Usuario"))
        self.lbl_contrasegnia.setText(_translate("InicioSesion", "Contraseña:"))
        self.btn_iniciar_sesion.setText(_translate("InicioSesion", "Iniciar Sesion"))
